mySecondUmbraco/Controllers/HomeController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace mySecondUmbraco.Controllers
{
    public class HomeController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Home/";

        public ActionResult RenderWork()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Work.cshtml");
        }

        public ActionResult RenderServices()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Services.cshtml");
        }

        public ActionResult RenderContent()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Content.cshtml");
        }

        public ActionResult RenderBlog()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Blog.cshtml");
        }
    }
}

mySecondUmbraco/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;



namespace mySecondUmbraco.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";

        public ActionResult RenderHeader()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Header.cshtml");
        }

        public ActionResult RenderHero()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Hero.cshtml");
        }

        public ActionResult RenderFooter()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Footer.cshtml");
        }
    }
}

mySecondUmbraco/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

<div id="fh5co-about">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
						<h3>About Us</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row row-bottom-padded-md">
					<div class="col-md-12 animate-box">
						<figure>
							<img src="/images/about-image.jpg" alt="Free HTML5 Bootstrap Template by FREEHTML5.co" class="img-responsive">
						</figure>
					</div>
				</div>
				<div class="row">
					<div class="col-md-8 col-md-offset-2 animate-box">
						<h3>Simple &amp; Humble Beginning</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut rerum perspiciatis, debitis pariatur atque vitae sed blanditiis nobis sint, reprehenderit quas, natus corrupti! Ipsum cum possimus corporis aut architecto! Delectus enim adipisci quidem possimus voluptates! Aut ut aliquid molestias laudantium.</p>
					</div>
				</div>
			</div>
		</div>
		<!-- END fh5co-about -->
		<div id="fh5co-content-section" class="fh5co-section-gray">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
						<h3>What Others Say</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="fh5co-testimonial text-center animate-box">
							<figure>
								<img src="/images/user-1.jpg" alt="user">
							</figure>
							<blockquote>
								<p>“Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn’t really do it, they just saw something. It seemed obvious to them after a while.”</p>
							</blockquote>
							<span>Steve Jobs, Apple Inc.</span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- fh5co-content-section -->
		<div id="fh5co-services-section">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
						<h3>What We Do</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row text-center">
					<div class="col-md-4 col-sm-4">
						<div class="services animate-box">
							<span><i class="icon-browser"></i></span>
							<h3>Web Development</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
					</div>
					<div class="col-md-4 col-sm-4">
						<div class="services animate-box">
							<span><i class="icon-mobile"></i></span>
							<h3>Mobile Apps</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
					</div>
					<div class="col-md-4 col-sm-4">
						<div class="services animate-box">
							<span><i class="icon-tools"></i></span>
							<h3>UX Design</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
					</div>
					<div class="col-md-4 col-sm-4">
						<div class="services animate-box">
							<span><i class="icon-video"></i></span>
							<h3>Video Editing</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
					</div>
					<div class="col-md-4 col-sm-4">
						<div class="services animate-box">
							<span><i class="icon-search"></i></span>
							<h3>SEO Ranking</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
					</div>
					<div class="col-md-4 col-sm-4">
						<div class="services animate-box">
							<span><i class="icon-cloud"></i></span>
							<h3>Cloud Based Apps</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END fh5co-services-section -->

mySecondUmbraco/Views/Blog.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

    <div id="fh5co-blog-section" class="fh5co-section-gray">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
					<h3>Read Our Blog</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4">
					<div class="fh5co-blog animate-box">
						<a href="#"><img class="img-responsive" src="/images/blog-1.jpg" alt=""></a>
						<div class="image-popup" href="#">
							<div class="prod-title">
								<h3><a href=""#>45 Minimal Worksspace Rooms for Web Savvys</a></h3>
								<span class="posted_by">Posted by: Admin</span>
								<span class="comment"><a href="">21<i class="icon-bubble22"></i></a></span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<a href="#" class="btn btn-primary">Read More</a>
							</div>
						</div> 
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="fh5co-blog animate-box">
						<a href="#"><img class="img-responsive" src="/images/blog-2.jpg" alt=""></a>
						<div class="image-popup" href="#">
							<div class="prod-title">
								<h3><a href=""#>45 Minimal Worksspace Rooms for Web Savvys</a></h3>
								<span class="posted_by">Posted by: Admin</span>
								<span class="comment"><a href="">21<i class="icon-bubble22"></i></a></span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<a href="#" class="btn btn-primary">Read More</a>
							</div>
						</div> 
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="fh5co-blog animate-box">
						<a href="#"><img class="img-responsive" src="/images/blog-3.jpg" alt=""></a>
						<div class="image-popup" href="#">
							<div class="prod-title">
								<h3><a href=""#>45 Minimal Worksspace Rooms for Web Savvys</a></h3>
								<span class="posted_by">Posted by: Admin</span>
								<span class="comment"><a href="">21<i class="icon-bubble22"></i></a></span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<a href="#" class="btn btn-primary">Read More</a>
							</div>
						</div> 
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="fh5co-blog animate-box">
						<a href="#"><img class="img-responsive" src="/images/blog-1.jpg" alt=""></a>
						<div class="image-popup" href="#">
							<div class="prod-title">
								<h3><a href=""#>45 Minimal Worksspace Rooms for Web Savvys</a></h3>
								<span class="posted_by">Posted by: Admin</span>
								<span class="comment"><a href="">21<i class="icon-bubble22"></i></a></span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<a href="#" class="btn btn-primary">Read More</a>
							</div>
						</div> 
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="fh5co-blog animate-box">
						<a href="#"><img class="img-responsive" src="/images/blog-2.jpg" alt=""></a>
						<div class="image-popup" href="#">
							<div class="prod-title">
								<h3><a href=""#>45 Minimal Worksspace Rooms for Web Savvys</a></h3>
								<span class="posted_by">Posted by: Admin</span>
								<span class="comment"><a href="">21<i class="icon-bubble22"></i></a></span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<a href="#" class="btn btn-primary">Read More</a>
							</div>
						</div> 
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="fh5co-blog animate-box">
						<a href="#"><img class="img-responsive" src="/images/blog-3.jpg" alt=""></a>
						<div class="image-popup" href="#">
							<div class="prod-title">
								<h3><a href=""#>45 Minimal Worksspace Rooms for Web Savvys</a></h3>
								<span class="posted_by">Posted by: Admin</span>
								<span class="comment"><a href="">21<i class="icon-bubble22"></i></a></span>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<a href="#" class="btn btn-primary">Read More</a>
							</div>
						</div> 
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- fh5co-blog-section -->

mySecondUmbraco/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

@foreach (IPublishedContent item in Model.Content.Children)
{
	if (item.DocumentTypeAlias == "hero")
	{
		@Html.Partial("_Hero", item)
	}
	else if (item.DocumentTypeAlias == "contact")
	{
		@Html.Partial("_Contact", item)
	}
}

mySecondUmbraco/Views/Hero.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Hero>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

mySecondUmbraco/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@


@foreach (IPublishedContent item in Model.Content.Children)
{
	if (item.DocumentTypeAlias == "hero")
	{
		@Html.Partial("_Hero", item)
	} else if (item.DocumentTypeAlias == "projectsHome")
	{
		@Html.Partial("_WorksHome", item)
	}
	else if (item.DocumentTypeAlias == "services")
	{
		@Html.Partial("_Services", item)
	}
	else if (item.DocumentTypeAlias == "about")
	{
		@Html.Partial("_Content", item)
	}
	else if (item.DocumentTypeAlias == "blog")
	{
		@Html.Partial("_Blog", item)
	}
}


@{
	//Html.RenderAction("RenderWork", "Home");

	//Html.RenderAction("RenderServices", "Home");

	//Html.RenderAction("RenderContent", "Home");

	//Html.RenderAction("RenderBlog", "Home");
}

mySecondUmbraco/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Optimization

@{
	Layout = null;
}

@* the fun starts here *@

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Guardian &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

	<!--
	  //////////////////////////////////////////////////////

	  FREE HTML5 TEMPLATE
	  DESIGNED & DEVELOPED by FREEHTML5.CO

	  Website: 		http://freehtml5.co/
	  Email: 			info@freehtml5.co
	  Twitter: 		http://twitter.com/fh5co
	  Facebook: 		https://www.facebook.com/fh5co

	  //////////////////////////////////////////////////////
	   -->
	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,300' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="/css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="/css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="/css/bootstrap.css">
	<!-- Superfish -->
	<link rel="stylesheet" href="/css/superfish.css">

	<link rel="stylesheet" href="/css/style.css">

	<!-- Modernizr JS -->
	<script src="/scripts/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9] -->
	<script src="/scripts/respond.min.js"></script>
	<![endif]-->

	@RenderSection("Head", false)
</head>

<body>

	@RenderSection("ScriptsTop", false)

	<div id="fh5co-wrapper">
		<div id="fh5co-page">

			@Html.Partial("_Header")

			@*@{ Html.RenderAction("RenderHeader", "SiteLayout"); }*@

			@*@{ Html.RenderAction("RenderHero", "SiteLayout"); }*@

			@RenderBody()

			@*@{ Html.RenderAction("RenderFooter", "SiteLayout"); }*@

			@Html.Partial("_Footer")

		</div>
		<!-- END fh5co-page -->

	</div>
	<!-- END fh5co-wrapper -->
	<!-- jQuery -->


	<script src="/scripts/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="/scripts/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="/scripts/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="/scripts/jquery.waypoints.min.js"></script>
	<!-- Stellar -->
	<script src="/scripts/jquery.stellar.min.js"></script>
	<!-- Superfish -->
	<script src="/scripts/hoverIntent.js"></script>
	<script src="/scripts/superfish.js"></script>

	@RenderSection("ScriptsBottom", false)

	<!-- Main JS (Do not remove) -->
	<script src="/scripts/main.js"></script>

</body>
</html>

mySecondUmbraco/Views/NormalPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<IPublishedContent>
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

@foreach (IPublishedContent item in Model.Content.Children)
{
	if (item.DocumentTypeAlias == "hero")
	{
		@Html.Partial("_Hero", item)
	}
	else if (item.DocumentTypeAlias == "work")
	{
		@Html.Partial("_Work", item)
	}
	else if (item.DocumentTypeAlias == "services")
	{
		@Html.Partial("_Services", item)
	}
	else if (item.DocumentTypeAlias == "about")
	{
		@Html.Partial("_Content", item)
	}
	else if (item.DocumentTypeAlias == "blog")
	{
		@Html.Partial("_Blog", item)
	}
}

mySecondUmbraco/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

mySecondUmbraco/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

mySecondUmbraco/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

mySecondUmbraco/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

mySecondUmbraco/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

mySecondUmbraco/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

mySecondUmbraco/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

mySecondUmbraco/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))